
insert into dbo.LookupState (StateCode, StateName) values ('AL', 'Alabama')
insert into dbo.LookupState (StateCode, StateName) values ('AK', 'Alaska')
insert into dbo.LookupState (StateCode, StateName) values ('AZ', 'Arizona')
insert into dbo.LookupState (StateCode, StateName) values ('AR', 'Arkansas')
insert into dbo.LookupState (StateCode, StateName) values ('CA', 'California')
insert into dbo.LookupState (StateCode, StateName) values ('CO', 'Colorado')
insert into dbo.LookupState (StateCode, StateName) values ('CT', 'Connecticut')
insert into dbo.LookupState (StateCode, StateName) values ('DE', 'Delaware')
insert into dbo.LookupState (StateCode, StateName) values ('FL', 'Florida')
insert into dbo.LookupState (StateCode, StateName) values ('GA', 'Georgia')
insert into dbo.LookupState (StateCode, StateName) values ('HI', 'Hawaii')
insert into dbo.LookupState (StateCode, StateName) values ('ID', 'Idaho')
insert into dbo.LookupState (StateCode, StateName) values ('IL', 'Illinois')
insert into dbo.LookupState (StateCode, StateName) values ('IN', 'Indiana')
insert into dbo.LookupState (StateCode, StateName) values ('IA', 'Iowa')
insert into dbo.LookupState (StateCode, StateName) values ('KS', 'Kansas')
insert into dbo.LookupState (StateCode, StateName) values ('KY', 'Kentucky')
insert into dbo.LookupState (StateCode, StateName) values ('LA', 'Louisiana')
insert into dbo.LookupState (StateCode, StateName) values ('ME', 'Maine')
insert into dbo.LookupState (StateCode, StateName) values ('MD', 'Maryland')
insert into dbo.LookupState (StateCode, StateName) values ('MA', 'Massachusetts')
insert into dbo.LookupState (StateCode, StateName) values ('MI', 'Michigan')
insert into dbo.LookupState (StateCode, StateName) values ('MN', 'Minnesota')
insert into dbo.LookupState (StateCode, StateName) values ('MS', 'Mississippi')
insert into dbo.LookupState (StateCode, StateName) values ('MO', 'Missouri')
insert into dbo.LookupState (StateCode, StateName) values ('MT', 'Montana')
insert into dbo.LookupState (StateCode, StateName) values ('NE', 'Nebraska')
insert into dbo.LookupState (StateCode, StateName) values ('NV', 'Nevada')
insert into dbo.LookupState (StateCode, StateName) values ('NH', 'New Hampshire')
insert into dbo.LookupState (StateCode, StateName) values ('NJ', 'New Jersey')
insert into dbo.LookupState (StateCode, StateName) values ('NM', 'New Mexico')
insert into dbo.LookupState (StateCode, StateName) values ('NY', 'New York')
insert into dbo.LookupState (StateCode, StateName) values ('NC', 'North Carolina')
insert into dbo.LookupState (StateCode, StateName) values ('ND', 'North Dakota')
insert into dbo.LookupState (StateCode, StateName) values ('OH', 'Ohio')
insert into dbo.LookupState (StateCode, StateName) values ('OK', 'Oklahoma')
insert into dbo.LookupState (StateCode, StateName) values ('OR', 'Oregon')
insert into dbo.LookupState (StateCode, StateName) values ('PA', 'Pennsylvania')
insert into dbo.LookupState (StateCode, StateName) values ('RI', 'Rhode Island')
insert into dbo.LookupState (StateCode, StateName) values ('SC', 'South Carolina')
insert into dbo.LookupState (StateCode, StateName) values ('SD', 'South Dakota')
insert into dbo.LookupState (StateCode, StateName) values ('TN', 'Tennessee')
insert into dbo.LookupState (StateCode, StateName) values ('TX', 'Texas')
insert into dbo.LookupState (StateCode, StateName) values ('UT', 'Utah')
insert into dbo.LookupState (StateCode, StateName) values ('VT', 'Vermont')
insert into dbo.LookupState (StateCode, StateName) values ('VA', 'Virginia')
insert into dbo.LookupState (StateCode, StateName) values ('WA', 'Washington')
insert into dbo.LookupState (StateCode, StateName) values ('WV', 'West Virginia')
insert into dbo.LookupState (StateCode, StateName) values ('WI', 'Wisconsin')
insert into dbo.LookupState (StateCode, StateName) values ('WY', 'Wyoming')